Tried to add patterns and something broke
wishlist.js:138 Uncaught TypeError: box.favColors.forEach is not a function
    at wishlist.js:138
    at Array.forEach (<anonymous>)
    at printList (wishlist.js:101)
    at HTMLButtonElement.onclick (wishlist.html:7)
(anonymous) @ wishlist.js:138
printList @ wishlist.js:101
onclick @ wishlist.html:7